/**
 * Admin — Reports module.
 *
 * Two parts:
 *   1) Generators — Daily / Weekly / Monthly presets + custom range.
 *      All date pickers are validated to disallow future dates.
 *   2) History — list of every report previously generated by an admin,
 *      stored in `public.reports`. Each row can be re-downloaded as PDF.
 */
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import AppShell from "@/components/AppShell";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { ADMIN_NAV } from "./nav";
import {
  format, subDays, startOfDay, eachDayOfInterval,
  startOfWeek, endOfWeek, startOfMonth, endOfMonth,
} from "date-fns";
import { downloadReport } from "@/lib/pdf";
import { Download, CalendarDays, CalendarRange, Calendar, History, FileText } from "lucide-react";
import { toast } from "sonner";

interface Booking {
  id: string;
  trip_id: string;
  status: "active" | "cancelled";
  created_at: string;
}
interface Trip {
  id: string;
  origin: string;
  destination: string;
  price_sar: number;
}
interface ReportRow {
  id: string;
  kind: "daily" | "weekly" | "monthly" | "custom";
  from_date: string;
  to_date: string;
  total_bookings: number;
  active_bookings: number;
  cancelled_bookings: number;
  revenue_sar: number;
  created_at: string;
}

interface Preset {
  key: "daily" | "weekly" | "monthly";
  label: string;
  description: string;
  icon: React.ReactNode;
  range: () => { from: Date; to: Date };
}

const PRESETS: Preset[] = [
  {
    key: "daily",
    label: "Daily report",
    description: "Bookings and revenue for today.",
    icon: <CalendarDays className="h-5 w-5" />,
    range: () => ({ from: startOfDay(new Date()), to: new Date() }),
  },
  {
    key: "weekly",
    label: "Weekly report",
    description: "Current calendar week (Mon → Sun).",
    icon: <CalendarRange className="h-5 w-5" />,
    range: () => ({
      from: startOfWeek(new Date(), { weekStartsOn: 1 }),
      to: endOfWeek(new Date(), { weekStartsOn: 1 }),
    }),
  },
  {
    key: "monthly",
    label: "Monthly report",
    description: "Current month from day 1 onwards.",
    icon: <Calendar className="h-5 w-5" />,
    range: () => ({ from: startOfMonth(new Date()), to: endOfMonth(new Date()) }),
  },
];

const KIND_LABEL: Record<ReportRow["kind"], string> = {
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
  custom: "Custom",
};

export default function AdminReports() {
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [trips, setTrips] = useState<Trip[]>([]);
  const [history, setHistory] = useState<ReportRow[]>([]);

  // Custom range — defaults to the last 30 days.
  const [from, setFrom] = useState(format(subDays(new Date(), 29), "yyyy-MM-dd"));
  const [to, setTo]     = useState(format(new Date(), "yyyy-MM-dd"));
  const [customKind, setCustomKind] = useState<"daily" | "weekly" | "monthly" | "custom">("custom");

  const loadHistory = async () => {
    const { data } = await (supabase as any)
      .from("reports")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(100);
    setHistory((data ?? []) as ReportRow[]);
  };

  useEffect(() => {
    (async () => {
      const [bRes, tRes] = await Promise.all([
        supabase.from("bookings").select("id, trip_id, status, created_at"),
        supabase.from("trips").select("id, origin, destination, price_sar"),
      ]);
      setBookings((bRes.data ?? []) as Booking[]);
      setTrips((tRes.data ?? []) as Trip[]);
      await loadHistory();
    })();
  }, []);

  const priceById = useMemo(
    () => new Map(trips.map((t) => [t.id, Number(t.price_sar)])),
    [trips],
  );

  /** Compute the report payload for a date range. */
  const buildPayload = (rangeFrom: Date, rangeTo: Date) => {
    const start = startOfDay(rangeFrom).getTime();
    const end   = startOfDay(rangeTo).getTime() + 86_400_000 - 1;
    const inRange = bookings.filter((b) => {
      const t = new Date(b.created_at).getTime();
      return t >= start && t <= end;
    });
    const active = inRange.filter((b) => b.status === "active");
    const revenue = active.reduce((s, b) => s + (priceById.get(b.trip_id) ?? 0), 0);
    const summary = {
      total: inRange.length,
      active: active.length,
      cancelled: inRange.length - active.length,
      revenue,
    };
    const days = eachDayOfInterval({ start: rangeFrom, end: rangeTo });
    const counts = new Map(days.map((d) => [
      startOfDay(d).toISOString(),
      { active: 0, cancelled: 0, revenue: 0 },
    ]));
    inRange.forEach((b) => {
      const k = startOfDay(new Date(b.created_at)).toISOString();
      const cell = counts.get(k);
      if (!cell) return;
      if (b.status === "active") {
        cell.active += 1;
        cell.revenue += priceById.get(b.trip_id) ?? 0;
      } else cell.cancelled += 1;
    });
    const daily = days.map((d) => ({
      day: format(d, "MMM d"),
      ...counts.get(startOfDay(d).toISOString())!,
    }));
    const m = new Map<string, number>();
    inRange.filter((b) => b.status === "active").forEach((b) => {
      const tr = trips.find((t) => t.id === b.trip_id);
      if (!tr) return;
      const k = `${tr.origin} → ${tr.destination}`;
      m.set(k, (m.get(k) ?? 0) + Number(tr.price_sar));
    });
    const routes = Array.from(m.entries())
      .map(([route, revenue]) => ({ route, revenue }))
      .sort((a, b) => b.revenue - a.revenue)
      .slice(0, 8);
    return { summary, daily, routes };
  };

  /** Generate, persist to history, and download the PDF. */
  const generate = async (
    rangeFrom: Date,
    rangeTo: Date,
    kind: "daily" | "weekly" | "monthly" | "custom",
  ) => {
    if (rangeFrom > new Date() || rangeTo > new Date()) {
      toast.error("Reports cannot include future dates.");
      return;
    }
    if (rangeFrom > rangeTo) {
      toast.error("'From' must be before 'To'.");
      return;
    }
    const { summary, daily, routes } = buildPayload(rangeFrom, rangeTo);

    const { data: { user } } = await supabase.auth.getUser();
    await (supabase as any).from("reports").insert({
      kind,
      from_date: format(rangeFrom, "yyyy-MM-dd"),
      to_date: format(rangeTo, "yyyy-MM-dd"),
      total_bookings: summary.total,
      active_bookings: summary.active,
      cancelled_bookings: summary.cancelled,
      revenue_sar: summary.revenue,
      generated_by: user?.id ?? null,
    });
    await loadHistory();

    downloadReport({
      from: format(rangeFrom, "yyyy-MM-dd"),
      to:   format(rangeTo,   "yyyy-MM-dd"),
      summary, daily, routes,
    });
    toast.success("Report generated and saved to history.");
  };

  /** Re-download a historic report (recomputed from current data). */
  const reDownload = (r: ReportRow) => {
    const f = new Date(r.from_date);
    const t = new Date(r.to_date);
    const { summary, daily, routes } = buildPayload(f, t);
    downloadReport({
      from: r.from_date, to: r.to_date, summary, daily, routes,
    });
  };

  const today = format(new Date(), "yyyy-MM-dd");

  return (
    <AppShell nav={ADMIN_NAV}>
      <div className="mb-6">
        <h1 className="text-2xl font-semibold">Reports</h1>
        <p className="text-sm text-muted-foreground">
          Generate operational reports and download them as PDF. Every report
          you generate is saved below in <span className="font-medium">History</span>.
        </p>
      </div>

      {/* Generators */}
      <div className="mb-6 grid gap-3">
        {PRESETS.map((p) => {
          const { from: f, to: t } = p.range();
          return (
            <Card key={p.key} className="flex items-center justify-between gap-4 p-4">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-md bg-primary/10 text-primary">
                  {p.icon}
                </div>
                <div>
                  <div className="font-medium">{p.label}</div>
                  <div className="text-xs text-muted-foreground">
                    {p.description} ·{" "}
                    <span className="text-foreground">
                      {format(f, "MMM d, yyyy")}
                      {format(f, "yyyy-MM-dd") !== format(t, "yyyy-MM-dd") &&
                        ` → ${format(t, "MMM d, yyyy")}`}
                    </span>
                  </div>
                </div>
              </div>
              <Button onClick={() => generate(f, t, p.key)}>
                <Download className="mr-1 h-4 w-4" /> Generate PDF
              </Button>
            </Card>
          );
        })}

        {/* Custom range */}
        <Card className="p-4">
          <div className="mb-3 flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-md bg-primary/10 text-primary">
              <CalendarRange className="h-5 w-5" />
            </div>
            <div>
              <div className="font-medium">Custom range report</div>
              <div className="text-xs text-muted-foreground">
                Pick any start and end date — future dates are blocked.
              </div>
            </div>
          </div>
          <div className="flex flex-wrap items-end gap-3">
            <div>
              <Label>Type</Label>
              <select
                className="block h-10 rounded-md border border-input bg-background px-2 text-sm"
                value={customKind}
                onChange={(e) => setCustomKind(e.target.value as typeof customKind)}
              >
                <option value="custom">Custom</option>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
                <option value="monthly">Monthly</option>
              </select>
            </div>
            <div>
              <Label>From</Label>
              <Input
                type="date"
                max={today}
                value={from}
                onChange={(e) => setFrom(e.target.value)}
              />
            </div>
            <div>
              <Label>To</Label>
              <Input
                type="date"
                min={from}
                max={today}
                value={to}
                onChange={(e) => setTo(e.target.value)}
              />
            </div>
            <Button
              onClick={() => generate(new Date(from), new Date(to), customKind)}
              disabled={!from || !to || from > to}
            >
              <Download className="mr-1 h-4 w-4" /> Generate PDF
            </Button>
          </div>
        </Card>
      </div>

      {/* History */}
      <Card className="overflow-hidden">
        <div className="flex items-center gap-2 border-b border-border px-4 py-3 text-sm font-medium">
          <History className="h-4 w-4 text-muted-foreground" /> History
          <span className="ml-auto text-xs text-muted-foreground">
            {history.length} report{history.length === 1 ? "" : "s"}
          </span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-muted/50 text-left text-xs text-muted-foreground">
              <tr>
                <th className="px-4 py-2">Type</th>
                <th className="px-4 py-2">Range</th>
                <th className="px-4 py-2">Bookings</th>
                <th className="px-4 py-2">Revenue (SAR)</th>
                <th className="px-4 py-2">Generated</th>
                <th className="px-4 py-2 text-right">Action</th>
              </tr>
            </thead>
            <tbody>
              {history.map((r) => (
                <tr key={r.id} className="border-t border-border">
                  <td className="px-4 py-2">
                    <Badge variant="secondary">{KIND_LABEL[r.kind]}</Badge>
                  </td>
                  <td className="px-4 py-2 whitespace-nowrap">
                    {format(new Date(r.from_date), "MMM d, yyyy")}
                    {r.from_date !== r.to_date && ` → ${format(new Date(r.to_date), "MMM d, yyyy")}`}
                  </td>
                  <td className="px-4 py-2 whitespace-nowrap">
                    {r.active_bookings} active · {r.cancelled_bookings} cancelled
                  </td>
                  <td className="px-4 py-2 tabular-nums">{Number(r.revenue_sar).toFixed(2)}</td>
                  <td className="px-4 py-2 whitespace-nowrap text-muted-foreground">
                    {format(new Date(r.created_at), "yyyy-MM-dd HH:mm")}
                  </td>
                  <td className="px-4 py-2 text-right">
                    <Button size="sm" variant="outline" onClick={() => reDownload(r)}>
                      <Download className="mr-1 h-3 w-3" /> PDF
                    </Button>
                  </td>
                </tr>
              ))}
              {history.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-4 py-8 text-center text-muted-foreground">
                    <FileText className="mx-auto mb-2 h-6 w-6 opacity-50" />
                    No reports generated yet — use the buttons above to create one.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </AppShell>
  );
}
